### ISSUE TITLE
Module 'rest_framework' has no attribute 'routers'

### ISSUE THREAD

**Issue by kolomenkin** [mkurnikov/djangorestframework-stubs#1]
Hi, you are doing great work!

The following code causes the problem for me

```
from rest_framework import routers
__ROUTER = routers.DefaultRouter()

```

```
main\rest_api\urls.py:4: error: Module 'rest_framework' has no attribute 'routers'
```

**Comment by mkurnikov** [comment]
Set 
```
ignore_missing_imports = True
```
in your `mypy.ini`.

**Comment by kolomenkin** [comment]
Thanks a lot, it helped for this particular case.

But in similar case it still gives another error:

```
from rest_framework import viewsets

class MyViewSet(viewsets.ModelViewSet):
    pass
```

```
main\rest_api\views.py:1: error: Module 'rest_framework' has no attribute 'viewsets'
main\rest_api\views.py:3: error: Class cannot subclass 'ModelViewSet' (has type 'Any')
```

**Comment by mkurnikov** [comment]
You can also set 
```
follow_imports = silent
```
Read this https://mypy.readthedocs.io/en/latest/running_mypy.html#follow-imports, it should give you the hint.

**Comment by kolomenkin** [comment]
Thanks a lot for your help!
I'm new to python type hinting and it is hard to understand right way of doing things.

**Comment by mkurnikov** [comment]
Addressed those particular errors here https://github.com/mkurnikov/djangorestframework-stubs/commit/bf73f18a23042743d8055445a8ac962ac1ae399f and here https://github.com/mkurnikov/djangorestframework-stubs/commit/554ee97240ebbc2404bbe68b90bf4f4692d283e3.
