### ISSUE TITLE
adding stubs fro test packages

### ISSUE THREAD

**Issue by chrismatheson** [mkurnikov/djangorestframework-stubs#6]
Hi, appreciate all the work. I just tried to install & use this in my project that's using DRF. However in the end i had to remove it because the test package stubs are missing. Not a huge deal in its own, but because im using an IDE it couldn't determine that `APISimpleTestCase` was an actual `TestCase` so all the nice features for running individual suites / tests started to fail :)

I'm not that familiar with python & mypy yet but when i am ill try and return and help out and add them in :)

**Comment by mkurnikov** [comment]
I'll try to fix it in a couple of days.

**Comment by mkurnikov** [comment]
That's a legitimate bug=) Thanks for trying out the project, by the way.

**Comment by mkurnikov** [comment]
Fixed in https://github.com/mkurnikov/djangorestframework-stubs/commit/95f14064245ee168e276fb530e4523f2b4844902
