### ISSUE TITLE
got warning in Pycharm on from rest_framework.authtoken.models import Token

### ISSUE THREAD

**Issue by A-Iskakov** [mkurnikov/djangorestframework-stubs#7]
An import 
`from rest_framework.authtoken.models import Token`
gets warning in Pycharm

**Comment by mkurnikov** [comment]
Those stubs are still missing, I'll address it a bit later.

**Comment by mkurnikov** [comment]
Should be fixed in the latest release.

**Comment by A-Iskakov** [comment]
many thanks, man!
