### ISSUE TITLE
Missing stubs for rest_framework.documentation

### ISSUE THREAD

**Issue by beruic** [mkurnikov/djangorestframework-stubs#8]
After installing `djangorestframework-stubs` I get errors on the following line:

```python
from rest_framework.documentation import include_docs_urls
```

**Comment by mkurnikov** [comment]
Got it, will be added in the next release.

**Comment by mkurnikov** [comment]
Fixed in https://github.com/mkurnikov/djangorestframework-stubs/commit/37a3218b000686e335e8cc822ec99d7702f818da
